config/routes.rb
Store::Application.routes.draw do
  captcha_route

  get "upload/index"

  match "upload/uploadFile"=>"upload#uploadFile"
  match "product/refresh"=>"products#refresh"
  resources :products

   root :to => 'products#index'

end

app/models/datafile.rb
class Datafile < ActiveRecord::Base
    attr_accessor :upload
  def self.save(upload)
    name = upload['datafile'].original_filename  
    current_user=Product.first.name 
    cmd="cd #{Rails.root}/public ; mkdir -p ./image/#{current_user}"
    system(cmd) 
    directory = 'public/image'
    
    # create the file path
    path = File.join(directory,current_user,name)
    # write the file
    File.open(path, "wb") { |f| f.write(upload['datafile'].read)}
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :avatar
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "images/:style/missing.png", :url  => "products/:id/:style/:basename.:extension", :path => ":rails_root/public/assets/products/:id/:style/:basename.:extension"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # reset captcha code after each request for security
  after_filter :reset_last_captcha_code!

  protect_from_forgery
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def refresh
    respond_to do |format|
        format.js
    end
  end
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    url = "www.baidu.com"
    @qr = RQRCode::QRCode.new(url, :size => 6, :level => 'q'.to_sym)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
      format.svg  { render :qrcode => request.url, :level => :l, :unit => 10 }
      format.png  { render :qrcode => request.url }
      format.gif  { render :qrcode => request.url }
      format.jpeg { render :qrcode => request.url }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])
#    @product.avatar = nil
#    @product.save
    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/upload_controller.rb
class UploadController < ApplicationController
  def index
    render :file=>"app/views/upload/uploadFile.html.erb"
  end

  def uploadFile
    post=Datafile.save(params[:upload])
    render :text=>"upload success"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">Some Store</a>
        <div class="nav-collapse">
          <ul class="nav pull-right">
            <li><%= link_to "Browse Products", products_path %></li>
            <li><%= link_to "Price List" %></li>
            <li><%= link_to "Contact Us" %></li>
            <li><%= link_to "Cart" %></li>
            <li class="dropdown">
               <a class="dropdown-toggle" id="dLabel" role="button" data-toggle="dropdown" data-target="#" href="/page.html">
                Dropdown
                <b class="caret"></b>
                </a>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                   <li><a tabindex="-1" href="#">Action</a></li>
                   <li><a tabindex="-1" href="#">Another action</a></li>
                   <li><a tabindex="-1" href="#">Something else here</a></li>
                   <li class="divider"></li>
                   <li><a tabindex="-1" href="#">Separated link</a></li>
                </ul>
             </li>
          </ul>
          <ul class="nav">
            <li><%= link_to "Browse Products", products_path %></li>
            <li><%= link_to "Price List" %></li>
            <li><%= link_to "Contact Us" %></li>
            <li><%= link_to "Cart" %></li>
            <li class="dropdown">
               <a class="dropdown-toggle" id="dLabel" role="button" data-toggle="dropdown" data-target="#" href="/page.html">
                Dropdown
                <b class="caret"></b>
                </a>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                   <li><a tabindex="-1" href="#">Action</a></li>
                   <li><a tabindex="-1" href="#">Another action</a></li>
                   <li><a tabindex="-1" href="#">Something else here</a></li>
                   <li class="divider"></li>
                   <li><a tabindex="-1" href="#">Separated link</a></li>
                </ul>
             </li>
          </ul> 
        </div>
      </div>
    </div>
  </div>

     <div class="container">
    <div class="row">
      <div class="span9"><%= yield %></div>
      <div class="span3">
        <h2>About Us</h2>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </div>
    </div>
  </div>


</body>
</html>

app/views/products/_captch.html.erb
 <% if false %>
  <% if request.post? %>
    <p><%= valid_captcha?(params[:captcha]) ? 'valid' : 'invalid' %> captcha</p>
  <% end %>
  <% end %>
  <p><%= captcha_tag %></p>
  

app/views/products/_form.html.erb
<div class="ajax-progress"></div>
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br />
    <%= f.file_field :avatar %>
  </div>
   <div id="captch">
   <%= render :partial => "captch" %>
   </div>
  <p><%= text_field_tag :captcha %></p><%= link_to "refresh", product_refresh_path(:format=>:js), :remote=>true %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<style type="text/css">
table {
  border-width: 0;
  border-style: none;
  border-color: #0000ff;
  border-collapse: collapse;
}
td {
  border-width: 0;
  border-style: none;
  border-color: #0000ff;
  border-collapse: collapse;
  padding: 0;
  margin: 0;
  width: 10px;
  height: 10px;
}
td.black { background-color: #000; }
td.white { background-color: #fff; }
</style>

<table>
<% @qr.modules.each_index do |x| %>
  <tr> 
  <% @qr.modules.each_index do |y| %>
   <% if @qr.dark?(x,y) %>
    <td class="black"/>
   <% else %>
    <td class="white"/>
   <% end %>
  <% end %>
  </tr>
<% end %>
</table>
<h1>Listing products</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= image_tag product.avatar.url(:medium) %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/refresh.js.erb
$("#captch").html('')
var content=$("<%= escape_javascript render(:partial => 'captch').html_safe %>")  
$("#captch").html(content)

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>
<h3>Upload a Photo</h3> 
<%= form_for @product, :html => {:multipart => true} do |f| %> 
  <p>
    <%= f.file_field :photo %>
  </p>
  <p>
    <%= f.submit "Upload" %>
  </p>
<% end %>
<%= image_tag @product.avatar.url(:original) %>
<%= image_tag @product.avatar.url(:medium) %>
<%= image_tag @product.avatar.url(:thumb) %>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/upload/index.html.erb
<h1>Upload#index</h1>
<p>Find me in app/views/upload/index.html.erb</p>

app/views/upload/uploadFile.html.erb
<h1>File Upload</h1>
<%= form_tag({:action => 'uploadFile'}, :multipart => true) do %>
<p><label for="upload_file">Select File</label>
<%= file_field 'upload', 'datafile' %></p>
<%= submit_tag "Upload" %>
<% end %>
<p>Upload your Video </p>
<div id="video_attachment"></div>
<style>
p {
   background-image: url('<%= asset_path("rails.png") %>');
}
</style>

<script type="text/javascript">
  $(function() {
    <% session_key = Rails.application.config.session_options[:key] %>
    var uploadify_script_data = {};
    var csrf_token = $('meta[name=csrf-token]').attr('content');
    var csrf_param = $('meta[name=csrf-param]').attr('content');

    uploadify_script_data[csrf_param] = encodeURI(encodeURIComponent(csrf_token));
    uploadify_script_data['<%= session_key %>'] = '<%= cookies[session_key] %>';

    $('#video_attachment').uploadify({
	'auto'				: false,
	'multi'				: false,
	'uploadLimit'		: 1,
	'formData'			: {'uid':'18'},
	'buttonText'		: '请选择图片',
	'height'			: 20,
	'width'				: 120,
	'removeCompleted'	: false,
	'swf'				: '<%= asset_path("uploadify.swf") %>',
	'uploader'			: '<%= upload_uploadFile_path %>',
	'fileTypeExts'		: '*.gif; *.jpg; *.jpeg; *.png;',
	'fileSizeLimit'		: '1024KB',
      'onUploadSuccess' : function(event, data){
        alert("Success!  Please be patient while the video processes.");
      },
      'onClearQueue' : function(queueItemCount) {
            alert( $('#img1') );
        },
      'onCancel' : function(file) {
            alert('The file ' + file.name + ' was cancelled.');
        }
    });
  });
</script>